### ISSUE TITLE
Tubing

### ISSUE THREAD

**Issue by fabriziofiorucci** [jakkra/Mars-Rover#1]
Hello, thank you for sharing this very interesting project: far as I can see the rocker bogie tubing is not printed but looks like standard pvc tubing: what thickness did you select?
Thank you

**Comment by fabriziofiorucci** [comment]
Solved! Measured from the f3d body

**Comment by jakkra** [comment]
Hi thanks!

I was just about to send you this:
![Capture](https://user-images.githubusercontent.com/4318648/70853831-78a0ba00-1eb3-11ea-989e-0c1e69797019.PNG)
Yes it's some standard PVC pipe I found to save some printing time.
In Fusion 360 modify -> change parameters you can see the diameters.
I do however doubt it's going to work just changing the setting there, so I suggest try using the same diameter.

**Comment by fabriziofiorucci** [comment]
Thank you! Just started printing the whole rover using asa-x filament

**Comment by jakkra** [comment]
Awesome, good luck! I'm sure thats better than the cheap standard PLA I have printed with.

**Comment by hoonkai** [comment]
@jakkra Hi What sort of adhesive did you use to attach the PVC and the parts together?

**Comment by fabriziofiorucci** [comment]
@hoonkai in case this can help, please see here https://github.com/jakkra/Mars-Rover/issues/12#issuecomment-620130493

**Comment by jakkra** [comment]
Hi @hoonkai, the fit is pretty tight but still needs something more to make it 100%, I just drilled a hole straight through and put a screw through like this: 
![IMG_20200427_200358](https://user-images.githubusercontent.com/4318648/80405023-550a6900-88c2-11ea-8854-15357d8fb23f.jpg)
