### ISSUE TITLE
Servos don't fit

### ISSUE THREAD

**Issue by BarryReid** [jakkra/Mars-Rover#10]
Hi Guys

I bought TowerPro MG946R's for the steering as stated in the readme but after printing the wheel rotors they don't seem to fit at all. Just wondering if I am missing something.

**Comment by jakkra** [comment]
The margins might be a bit tight, and differences between printers could cause servos to not fit maybe. Is it way off, or could you sand the print a bit to get it to fit?  If you only printed one wheel rotator, then you can in Fusion increase the margin a bit. 

@fabriziofiorucci how did they fit for you?

**Comment by BarryReid** [comment]
Ye its quite a bit off and my printer is pretty accurate. I see in the cad model the server you have a model for is the MG996R not the MG946R like you have recommended in the docs. Could there be a difference there?

**Comment by fabriziofiorucci** [comment]
Hello,

margins are a bit tight indeed, but the overall assembly has to be sturdy, so it makes sense. I use a Creality Ender 3 and in some cases my servos (TowerPro MG996R) fit perfectly, in some other cases I needed to use a dremel with a sandpaper tip to allow for a bit more space. I didn't print/use the wheel rotator, I decided to use the stock aluminium rotator that comes with the servo.

![IMG_9587](https://user-images.githubusercontent.com/58330741/79951670-68a87080-8479-11ea-84cd-44bcbddab209.jpg)
![IMG_0451](https://user-images.githubusercontent.com/58330741/79951693-7231d880-8479-11ea-88a2-fc2e1f86d984.jpg)

**Comment by fabriziofiorucci** [comment]
![IMG_8718](https://user-images.githubusercontent.com/58330741/79951771-9ab9d280-8479-11ea-86e5-1de0ebf48096.jpg)
![IMG_8719](https://user-images.githubusercontent.com/58330741/79951783-a1484a00-8479-11ea-8990-8898ac3a6df0.jpg)

**Comment by BarryReid** [comment]
Ye those MG996R's must be a different size, you may want to update your doc on the front page as the MG946R's are quite a long way off (not just a snug fit) their mounting holes also don't line up.

![IMG_1845](https://user-images.githubusercontent.com/2881645/79981304-cffd0980-84e7-11ea-8c6e-7890ac504883.jpg)

**Comment by jakkra** [comment]
I pretty much asumed that MG996R's and MG946R's  are same, as I on the arm used both interchangeable. You can just bend those "pins/mounting holes" off from the print. I did that now I remember. Will work anyway. 

Will update readme.

**Comment by BarryReid** [comment]
No servers are still too big to fit even with a bit of force :) I will try shaving off some plastic from the part and see how its goes.

**Comment by jakkra** [comment]
Like @fabriziofiorucci says, most parts in the rover work better if they are a tight fit. Some part might need some sanding and force to fit. If you are very far off, then come back and I'll update the model to give a litte more room for the servos.

**Comment by fabriziofiorucci** [comment]
If I can add a bit/if this can be useful: I printed the rocker bogie assembly and wheels using ASA-X and my homebuilt heated printer enclosure (without it I can't simply print ASA-X due to cracking/warping) and after printing there is some shrinkage anyway, so steering servos were a bit tight (some sanding solved that).
When printing the body and arm I went for PLA and here warping/shrinking is virtually non-existing: when fitting the servos I needed to sand it even more if compared to the rocker bogie.

**Comment by jakkra** [comment]
I will increase the margins around some servos next time I'm working on the Rover model (unless @BarryReid can't sand around it)

By the way a little teaser: 
![93142698_548545269380639_6694265280291405824_n (1)](https://user-images.githubusercontent.com/4318648/80148891-02753800-85b6-11ea-98ed-c9392c4f7f0d.jpg)
![IMG_1267](https://user-images.githubusercontent.com/4318648/80148894-043efb80-85b6-11ea-99ef-4195c6e6a241.jpg)

**Comment by fabriziofiorucci** [comment]
This is super cool! When are you going to post the f3d files? ;-)
At the end of the day did you go for LoRa+WiFi?

**Comment by BarryReid** [comment]
Hey, ye if we could get a bit more space in the model that would be great, I need to sand so much that the walls of the print are almost non existent. I think this version of the servo is just a bit wider than the MG996R

**Comment by BarryReid** [comment]
When I get home I will send you the measurements of the MG946R

**Comment by jakkra** [comment]
Ok, that's a bit to much to sand, I will update the model tomorrow! I'll compare it with my servos and see how off it is.

For the controller, yes I went with both wifi and lora. Code, CAD and website for the phone is all about 80% done. Have not finished final design of the back of the controllers yet. I'll probably finish it up the next 2 weeks and make the repository public.

**Comment by jakkra** [comment]
Hi @BarryReid, I realised the servo model I have used for reference is a about 1mm smaller than the real one.
I measured my MG946R and MG99R and they have the exact same size. I made some more room in the "`original_wheel_rotor`" parts. Will those dimentions work for you? Should give about 0.25mm clearance.
![Capture1](https://user-images.githubusercontent.com/4318648/80284757-b09cf100-8720-11ea-8a04-cde03b663603.JPG)
![Capture](https://user-images.githubusercontent.com/4318648/80284758-b1358780-8720-11ea-973b-ea0a8d971cd1.JPG)

**Comment by BarryReid** [comment]
Mate that's should be perfect! Did you make the change on the back and front rotors? I tried to download to check but cant see the updated CAD model in the GIT.

**Comment by jakkra** [comment]
No, I didn't upload, wanted to get ok from you first. Will update asap.

**Comment by BarryReid** [comment]
Thanks mate, did you make the change on the back and the front rotors?

**Comment by jakkra** [comment]
Yes all 4, exporting now.

**Comment by BarryReid** [comment]
Hey @jakkra thanks so much for making those changes. I printed this part again overnight and have just completed a test fit. 

It now however seems to be a bit loose. Just wondering if you expanded it by a total of 1mm or if you did 1mm on each side?

I think if we made it half way between what it is now and what it was, it would be prefect.

Hope the feedback helps.

**Comment by jakkra** [comment]
No, I did 0.5 on each side, so in total 1mm. If it can move inside then it's a problem, but otherwise I don't think your print is wasted, it should be hold in place when servo head I screwed in place. But anyway I'll update the model tonight with 0.25mm on each side instead of 0.5.

**Comment by BarryReid** [comment]
Yip it moved ever so slightly. I think 0.25 on each side will be the perfect amount. The print should not be wasted as I will just glue in some single layer shims on each side of the servo. I will print the final rotor once you have updated the CAD and let you know the outcome.

Thanks

**Comment by jakkra** [comment]
Feel free to print the final rotor now, I have now updated the dimentions.

**Comment by k4m454k** [comment]
![image](https://user-images.githubusercontent.com/20520240/82732914-162ccf00-9d19-11ea-893b-799294113dd6.jpeg)

Same problem with TowerPro MG996R
![image](https://user-images.githubusercontent.com/20520240/82732969-555b2000-9d19-11ea-9396-8e4a41e3afe3.jpeg)

I redid original_wheel_rotor element, changing the distance between the mounting pins

![image](https://user-images.githubusercontent.com/20520240/82733066-05c92400-9d1a-11ea-8ee8-1d28c4035041.jpeg)

**Comment by BarryReid** [comment]
Ye, I just snapped them off, drilled some tiny pilot holes and screwed them in with a few self tappers.

**Comment by k4m454k** [comment]
> Ye, I just snapped them off, drilled some tiny pilot holes and screwed them in with a few self tappers.

Barbarian =)

**Comment by jakkra** [comment]
Yeah just snap them off, seems as the distance between the holes are a bit different between some brands of MG966R. They don't really do anything.

**Comment by k4m454k** [comment]
> Yeah just snap them off, seems as the distance between the holes are a bit different between some brands of MG966R. They don't really do anything.  


I just redid this element and re-printed it.  the perfectionist inside me rejoices

![image](https://user-images.githubusercontent.com/20520240/82740934-fc5dad00-9d55-11ea-8abd-6ff86167d847.jpeg)

**Comment by jakkra** [comment]
@k4m454k hehe great! There are some things that are not perfect yet in the build, so you might need to compromise with your inner perfectionist some time later :wink:
