### ISSUE TITLE
Connecting 2 body halves

### ISSUE THREAD

**Issue by BarryReid** [jakkra/Mars-Rover#14]
Hey Guys

When connecting the 2 body halves there seems to only be connectors at the top. How are others connecting the body halves together at the bottom to stop them coming apart?

**Comment by jakkra** [comment]
Like this: 
![IMG_20200509_095618](https://user-images.githubusercontent.com/4318648/81467810-80068e00-91db-11ea-8314-77618cd9ee8a.jpg)

**Comment by BarryReid** [comment]
Perfect! Thanks
