### ISSUE TITLE
How to print head top connector & head rotator

### ISSUE THREAD

**Issue by fabriziofiorucci** [jakkra/Mars-Rover#17]
I'm trying to figure out how to print the head top connector & head rotator: I see that some bodies need to be exported as a single stl. One thing that is not clear to me is what bodies need to be exported/printed together in the red area here below:

![Screenshot_20200622_231752](https://user-images.githubusercontent.com/58330741/85336330-b9226580-b4de-11ea-81d1-acf7f183af9e.png)

Any hint? Thank you :)

**Comment by jakkra** [comment]
Just print the parts seperate and glue them together. I also removed some parts that I did not end up using, so please refer to updated CAD model in 1446ce1866cb28418cfaf15fcf79e33b03aeff84
![head_fixed](https://user-images.githubusercontent.com/4318648/85433829-5506ac80-b585-11ea-910b-a0c3592b6b3d.JPG)

Edit: Ignore that bearing I accidentally displayed

**Comment by fabriziofiorucci** [comment]
That's clear now, thank you!
