### ISSUE TITLE
What 12V to 5V switching voltage regulators do you use ?

### ISSUE THREAD

**Issue by Smarty-pro** [jakkra/Mars-Rover#18]
First off thanks for all the hard work you have put into this project. I am interested in building this, but I am having issues sourcing a 12v-to-5v-switching-voltage-regulators. I would like to know which ones you choose to go with.

**Comment by jakkra** [comment]
Hi, I use buck converters like those https://www.amazon.com/dp/B01MQGMOKI/ref=psdc_10967761_t1_B0758ZTS61 They can be found on many other places too.

**Comment by Smarty-pro** [comment]
Thank you :)
