### ISSUE TITLE
What RC receiver and transmitter do you use 

### ISSUE THREAD

**Issue by Smarty-pro** [jakkra/Mars-Rover#19]
Once again,thanks for all the hard work you have put into this project. I am interested in building this, but I am having issues sourcing a RC receiver and transmitter. I would like to know which ones you choose to go with.

**Comment by jakkra** [comment]
I use this one: https://hobbyking.com/en_us/turnigy-tgy-i6-mode-2-afhds-transmitter-and-6ch-receiver.html?queryID=273329baae26b5897bf8920bfd3a06de&objectID=45922&indexName=hbk_live_magento_en_us_products
But you can pretty much use any typical RC transmitter/receiver, they all work the same.

**Comment by Smarty-pro** [comment]
nice
