### ISSUE TITLE
Electronics schematics

### ISSUE THREAD

**Issue by fabriziofiorucci** [jakkra/Mars-Rover#2]
Hello, could you share the electronics schematics?
I’m building the electronics based on a raspberry zero and that would come handy.

Thanks!

**Comment by jakkra** [comment]
I did draw a not very detailed, but good enough psuedo schematic a while ago. This was from before I added the arm and head. Now I have a I2C servo expander which all servos are connected to for saving pins on the ESP32. 
![Capture](https://user-images.githubusercontent.com/4318648/70862537-f90bfd00-1f3d-11ea-8e0a-0652710dfc8b.JPG)

**Comment by fabriziofiorucci** [comment]
That’s a good starting point: what ESCs do you use?

**Comment by fabriziofiorucci** [comment]
I have a fully working design using 6 L298N drivers for the six dc motors, I’m evaluating whether to switch to ESCs

**Comment by jakkra** [comment]
I'm using 2 of those with 3 motors connected to each of them
https://hobbyking.com/en_us/hobbyking-x-car-45a-brushed-car-esc.html
So I don't have control of each motor individually, only each side. 
I don't see a problem using 6 L298N as long as your DC motors doesn't draw more than 2A under load.

**Comment by fabriziofiorucci** [comment]
Thanks: I actually am revamping a former rover I built using aluminium instead of plastic, and a lead acid battery instead of LiPO, with the aim of getting a self guided rover using a control software written in Java. Spare time permitting I might upload some contribution to add distance sensors, lidar etc.

**Comment by jakkra** [comment]
Awesome! I'll also add more sensors after I finish the designing and printing the "back" parts of the rover.

I'm thinking of giving https://nasa.github.io/openmct/ a try for ground control software (the UI). I'm also looking for a new radio to get better range and to be able to stream low res video from ~1000m distance. Yet to find a suitable radio technology.

**Comment by fabriziofiorucci** [comment]
The openmct project looks quite interesting: on my existing rover I added a GPS receiver and a digital compass and accelerometer, they work quite fine. Saving weight switching from aluminium to ASA and from lead battery to LiPO I might be able to put more stuff on it.
I'm experimenting a bit with LoRA for long range telemetry, but it's way too slow for video streaming, please keep me posted on your findings in that area.

**Comment by fabriziofiorucci** [comment]
Hello, for the sake of curiosity, what kind of DC-DC stepdown converter do you use for servos? I'm running on MG996R that have a stall current of ~2.5A so I was wondering, additionally, if you're using one stepdown converter per servo or what else.

Thank you

**Comment by jakkra** [comment]
Hi, I'm using variable buck converters like those: https://www.amazon.com/dp/B01MQGMOKI/ref=psdc_10967761_t1_B0758ZTS61
One for each servo (which is kind of a pain)

**Comment by fabriziofiorucci** [comment]
Thank you!

**Comment by fabriziofiorucci** [comment]
![IMG_0304](https://user-images.githubusercontent.com/58330741/77268457-4539ac80-6ca6-11ea-8159-481e8fab33e6.JPG)

Electronics work in progress...

- main board with Raspberry Zero, GPS receiver, magnetometer/accelerometer and ADC for distance sensors
- rocker bogie board with PWM controller for steering servos and control logic for L298N boards

**Comment by jakkra** [comment]
Looking good! I finished re-routing my wires so now everything is inside. Currently in progress building a controller using Lora.

**Comment by fabriziofiorucci** [comment]
LoRa is in my todo list: will you use it for both control and telemetry? Would you mind sharing some details? I guess you’ll use arduino/wemos, I’ll try the Raspberry way

**Comment by jakkra** [comment]
My plan is to use it both for control and telemetry, however I have not yet experimented to see how much the lag is. The idea is to use WiFi control when the rover is close and  switch over to Lora when range increases. I'm going to use two TTGO LORA32, replacing the ESP32 dev kit in the Rover with this board with an ESP32 + Lora transceiver and the other board will be in the controller.

**Comment by fabriziofiorucci** [comment]
That sounds really interesting. Please keep us posted!

**Comment by fabriziofiorucci** [comment]
![IMG_0340](https://user-images.githubusercontent.com/58330741/77837221-8fb3a100-715e-11ea-96ee-2c0d73ab4a30.JPG)
![IMG_0338](https://user-images.githubusercontent.com/58330741/77837227-a8bc5200-715e-11ea-9f51-4854a947055e.JPG)

main board and rocker bogie board assembled and tested, ready to be installed

**Comment by fabriziofiorucci** [comment]
![IMG_0367](https://user-images.githubusercontent.com/58330741/78413015-e2390580-7615-11ea-9bd6-67bd4950cf97.JPG)

Ready for testing

**Comment by jakkra** [comment]
Looks clean! My current progress: 
![Capture](https://user-images.githubusercontent.com/4318648/78721491-f471b700-7927-11ea-825e-6724b33b9120.JPG)
Will have a tablet holder on top also for telematics display.

**Comment by fabriziofiorucci** [comment]
it looks great! Will you share the f3d model?

**Comment by jakkra** [comment]
Of course!

**Comment by fabriziofiorucci** [comment]
![rover-2 0-high-level](https://user-images.githubusercontent.com/58330741/78766141-2b2be980-7989-11ea-86bd-cc41c400560a.jpg)

My high level electronics design, based on Raspberry Zero WH and I2C everywhere.

**Comment by fabriziofiorucci** [comment]
![raw_IMG_0500](https://user-images.githubusercontent.com/58330741/80188252-303b9a80-8611-11ea-835b-9a9248fd4ed4.jpg)

Arm and head control board

**Comment by fabriziofiorucci** [comment]
![IMG_0516](https://user-images.githubusercontent.com/58330741/80190707-02f0eb80-8615-11ea-81ad-aa1d89749b2b.JPG)
