### ISSUE TITLE
STL files ?

### ISSUE THREAD

**Issue by Smarty-pro** [jakkra/Mars-Rover#20]
I have a Linux computer, so I have not Fusion 360. Can I have the STL files please ?

**Comment by jakkra** [comment]
Hi, two reasons I don't have the STL files exported.
1. There are no build instructions, looking at the Fusion project is pretty much the way to build the rover. Without having the Fusion project on your computer it will be very hard to know how the parts should be put together. I don't recommend trying out this project without Fusion 360 to browse around and study how to build it.
2. There are many STL files to export and I don't want to have to keep them in sync with the Fusion project.

**Comment by Smarty-pro** [comment]
Okay
