### ISSUE TITLE
Openmct

### ISSUE THREAD

**Issue by Smarty-pro** [jakkra/Mars-Rover#22]
Hello, I recently found a next-generation mission control framework for visualization of data on desktop and mobile devices developed by NASA. This is the link https://nasa.github.io/openmct/

**Comment by Smarty-pro** [comment]
It could help you in the web interface of your rover

**Comment by jakkra** [comment]
Hi, thanks, I'm aware of that, I first planned to use it, but ended up doing something simple myself instead.
