### ISSUE TITLE
Arm missing from F3D CAD file

### ISSUE THREAD

**Issue by kevwilde** [jakkra/Mars-Rover#27]
Hi, I checked out the last version for the CAD file but I can only find the arm_holder component in there .. Is there a seperate location for the arm?

Thank you so much for this design!

**Comment by jakkra** [comment]
Hi, looks like I accidentally hid the arm parts when exporting the model, so it's still there, just hidden. So for now you can just go in like in the image and click the eye to show all arm components. I'll update the model later with the arm showm by default.
![Capture-show-arm](https://user-images.githubusercontent.com/4318648/198822877-c491f438-03fd-4cb8-8be1-0b855f5f34a3.PNG)
