### ISSUE TITLE
Best support type to slice & print body

### ISSUE THREAD

**Issue by fabriziofiorucci** [jakkra/Mars-Rover#4]
Hello,

I'm proceeding with all prints, and when it comes to the body I wonder what's the most efficient support type to use when slicing stl files: I'm using Cura and I usually use the default line with 10% spacing. Any hint here/what have you used?

Thank you

**Comment by jakkra** [comment]
I'm using Slic3r/PrusaSlicer, for supports I have just used the default ones in my slicer, so can't help you with which are best in Cura. Most parts don't need supports or just need some very simple ones. If you can give me a specific part, I can probably figure out how I printed it and send a image from my slicer.

**Comment by fabriziofiorucci** [comment]
Hi, thank you. Most parts are perfectly designed to require a minimum amount of supports (good job!). The only parts I would need a hint is the main body (rover_body_front and the back part), it's quite large and I would like to minimize filament waste by optimizing the (large) support area.

**Comment by jakkra** [comment]
I'll be home in an hour ish, will send you some images then.

**Comment by fabriziofiorucci** [comment]
Thank you!

**Comment by jakkra** [comment]
No supports needed for the front, printed fine on my MK3, should be fine on your Ender 3 too.
![front](https://user-images.githubusercontent.com/4318648/71912207-60038700-3175-11ea-9b6c-5f43c24635c1.jpg)
Only required supports for back are those two.
![back](https://user-images.githubusercontent.com/4318648/71912209-60038700-3175-11ea-8fad-94a1a0a3c6a3.jpg)

**Comment by fabriziofiorucci** [comment]
Thank you again! Cura tells me that I'm really hitting the width limit of the print bed and hence I should print it lying on one side. I'll try to fiddle with some parameters to print it the way you did. I'll keep you posted.

**Comment by jakkra** [comment]
Yeah I designed it pretty much to be as big as I could print. You can in worst case just make the main rover body a cm och 2 shorter to make it fit.

**Comment by fabriziofiorucci** [comment]
Hi, I managed to fix the printing area. I was wondering what infill and layer thickness you used. I would go for 20% and 0.24, that would be roughly 500g of filament and a couple of days of printing time.
Thank you

**Comment by jakkra** [comment]
Great! I used 0.2mm layer thickness, and fairly low infill, maybe 5%. If i recall correctly the main body took about a day for each half to print.

**Comment by fabriziofiorucci** [comment]
Thank you, I’ll try with that!

**Comment by jakkra** [comment]
I looked a bit closer on my Rover and see that I used 3 perimeters for the bodies, instead of default 2.

**Comment by fabriziofiorucci** [comment]
Thank you! I’ll change slicer settings accordingly

**Comment by fabriziofiorucci** [comment]
![IMG_9144](https://user-images.githubusercontent.com/58330741/72667772-b8614100-3a1f-11ea-849a-2f0f7a30cc6e.jpg)

currently printing the first half of the body: it takes the whole print area, thank you again!

**Comment by fabriziofiorucci** [comment]
![Image](https://i.imgur.com/iw8CQup.jpg)

Body and rocker bogie prints came out perfect, next step: putting together the electronics

**Comment by fabriziofiorucci** [comment]
Had some cracking issues while printing the body with ASA, so I switched back to PLA

**Comment by jakkra** [comment]
Wow that's awesome! Feels weird to see it on other than my colors, but it looks really good 👍 
Good luck with the electronics, that's the easy part IMO :)

Here's a peek in what I'm currently working on, upgrading the wheels to flexible wheels for better grip (also upgradade to Rover 2020 look of the wheels, however I prefer the look of the old ones, but printing the old style in flex filament didn't turn out so good).
![IMG_20200222_204757](https://user-images.githubusercontent.com/4318648/75098368-92e2cc80-55b5-11ea-8697-0d98b24755fb.jpg)

I also decided to finally clean up the wiring a bit, work in progress.
![IMG_20200222_205152](https://user-images.githubusercontent.com/4318648/75098370-96765380-55b5-11ea-8204-9273f62a50be.jpg)

PS. I'll re-open this issue for better visablity for others :)

**Comment by fabriziofiorucci** [comment]
Flexible wheels look great! I'm quite curious to see how ASA will react to friction when I start letting it run. Did you print the flexible part in TPU?

**Comment by jakkra** [comment]
I think the ASA will do pretty well, I do not se much wear on my PLA wheels, and ASA should be comparable if not a bit stronger.
I actually don't know, bought it from a local store and it's unlabeled, but I would guess it's TPU. It's properties seems to match TPU.
