### ISSUE TITLE
STL Files

### ISSUE THREAD

**Issue by BarryReid** [jakkra/Mars-Rover#7]
Hey, just wondering if there are any pre generated STL files available or if everyone is just creating their own from the CAD?

**Comment by jakkra** [comment]
Hi, I have not generetaed the STL files, and I don't really want to do that every time I update something. So yes, the idea is to download the Fusiom 360 project and export the STLs from there.

**Comment by BarryReid** [comment]
All good! Just wanted to make sure I was not missing something.

**Comment by Smarty-pro** [comment]
Hey, @jakkra I just found the 3d model of Curiosity made by NASA if you want to make your rover design more realistic https://github.com/nasa/NASA-3D-Resources/tree/master/3D%20Models/Curiosity%20(Clean)

**Comment by jakkra** [comment]
@Smarty-pro Cool!
